### PR TITLE
Revert "feat: add detector thresholds (minimum energy deposit)"

### PR DESCRIPTION
**Pull request by veprbl**
Reverts eic/npsim#9

See https://chat.epic-eic.org/main/pl/szkezeezwjnb3fiaiihg8ze87o
I can confirm that EEEMCal is performing very poorly as of 23.08.0 campaign.

### CODE REVIEW

**Comment by wdconinc** [comment]
Does this PR, combined with https://github.com/eic/EICrecon/pull/890, leave us in a satisfactory situation for 23.09? What about the calorimeters? We would be running completely thresholdless again, which can't seem right. Will there be a PR to add those thresholds to EICrecon in time for 23.09?

**Comment by kkauder** [comment]
> Does this PR, combined with [eic/EICrecon#890](https://github.com/eic/EICrecon/pull/890), leave us in a satisfactory situation for 23.09? What about the calorimeters? We would be running completely thresholdless again, which can't seem right. Will there be a PR to add those thresholds to EICrecon in time for 23.09?

The calo thresholds are less obvious and need DSC input.

**Comment by Chao1009** [comment]
A threshold at a few MeV in the calorimeter seems too high at the simulation level.
Such a few-MeV threshold is typically applied at the readout level (e.g., a PMT), which accumulates the energy (photons) from dozens of secondary particles.

**Comment by wdconinc** [comment]
We know. The question is what are we going to do about it, who is going to do it, and when.

**Comment by Chao1009** [comment]
> We know. The question is what are we going to do about it, who is going to do it, and when.

I strongly feel this should be the responsibility of each DSC since this value is strongly dependent on the calorimeter materials and the readout (e.g., what's the minimum energy a particle needs to generate some light that will be collected).

**Review by Chao1009 — APPROVED** [review]
For now, I think we have to run the calorimeters thresholdlessly.

**Comment by veprbl** [comment]
> For now, I think we have to run the calorimeters thresholdlessly.

Even before this, we already had thresholds implemented at the reconstruction stage.

**Comment by veprbl** [comment]
Filed eic/EICrecon#895

**Pull request merged**
